---
# tasks file for builder
- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - default-jdk
    - maven

- name: git pull
  git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/boxfuse-sample-java-war-hello

- name: build boxfuse war
  command: mvn package -f /home/boxfuse-sample-java-war-hello

- name: copy war file
  synchronize:
    mode: pull
    src: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
    dest: /var/lib/tomcat8/webapps/hello-1.0.war
    delegate_to: "{{item}}"
    with_items: "{{groups['web']}}"   

    #со всеми машинами группы или
    #delegate_to: "{{groups['web'][0]}}"
