---
# tasks file for builder
- name: install packages on "{{ansible_nodename}}"
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - git
    - default-jdk
    - maven

- name: git pull
  git: repo={{git_source}} dest={{dest_folder}}

- name: build boxfuse war
  command: mvn package -f {{dest_folder}}


