---
# tasks file for web
- name: ensure tomcat package is present on "{{ansible_nodename}}"
  apt: pkg=tomcat8 state=present update_cache=yes
 
- name: copy war file
  synchronize:
    mode: push
    src: "{{source_folder}}/hello-1.0.war"
    dest: "{{dest_folder}}/hello-1.0.war"
  delegate_to: "{{item}}"
  with_items: "{{groups['build']}}"
  when: wname=="web_hello"
  notify:
    - restart tomcat8
